### ISSUE TITLE
Question about updating the tree

### ISSUE THREAD

**Issue by Dankerprouduct** [Auios/Auios.QuadTree#2]
How do you update which leaf the item is in in your demo GIFs? Is this done automatically, or do you have to remove and re-add the item to the tree if it is beyond the limits of its current node?

**Comment by Auios** [comment]
Every frame I destroy and rebuild the entire QuadTree.
This is not ideal for a real application but just happened to be how I implemented it for the demo since it was a lightweight simulation. Ideally you'll rebuild it only when you need to or at larger time intervals.
But overall - you will rebuild the entire QuadTree, not just a section of it.
In the future it would be nice to be able to select a region of the tree and clear it, then only re-insert items that are in that space which you just reset.

**Comment by Dankerprouduct** [comment]
Thanks!
